const initializeBankList = (filter) => {
    const bankList = {
      stalkbri: 'Bank BRI',
      stalkmandiri: 'Bank Mandiri',
      stalkbni: 'Bank BNI',
      stalkbtn: 'Bank BTN',
      stalkbjb: 'Bank BJB',
      stalkdki: 'Bank DKI',
      stalkbpddiy: 'Bank BPD D.I.Y',
      stalkjateng: 'Bank Jateng',
      stalkjatim: 'Bank Jatim',
      stalkjambi: 'Bank Jambi',
      stalkaceh: 'Bank Aceh',
      stalksumut: 'Bank Sumut',
      stalksumbar: 'Bank Sumbar',
      stalkkepri: 'Bank Kepri',
      stalksumselbabel: 'Bank Sumsel dan Babel',
      stalklampung: 'Bank Lampung',
      stalkkalsel: 'Bank Kalsel',
      stalkkalbar: 'Bank Kalbar',
      stalkkaltim: 'Bank Kaltim',
      stalkkalteng: 'Bank Kalteng',
      stalksulsel: 'Bank Sulsel',
      stalksulut: 'Bank Sulut',
      stalkntb: 'Bank NTB',
      stalkbali: 'Bank Bali',
      stalkntt: 'Bank NTT',
      stalkmaluku: 'Bank Maluku',
      stalkpapua: 'Bank Papua',
      stalkbengkulu: 'Bank Bengkulu',
      stalksulteng: 'Bank Sulteng',
      stalksultra: 'Bank Sultra',
      stalkbanten: 'Bank Banten',
      stalkeksporindonesia: 'Bank Ekspor Indonesia',
      stalkdanamon: 'Bank Danamon Indonesia',
      stalkpermata: 'Bank Permata',
      stalkbca: 'Bank BCA',
      stalkmaybank: 'Bank Maybank',
      stalkpanin: 'Bank Panin',
      stalkartanigakencana: 'Bank Arta Niaga Kencana',
      stalkcimbniaga: 'Bank CIMB Niaga',
      stalkuob: 'Bank UOB Indonesia',
      stalklippo: 'Bank Lippo',
      stalkocbcnisp: 'Bank OCBC NISP',
      stalkmulticor: 'Bank Multicor',
      stalkarthagraha: 'Bank Artha Graha',
      stalkpesonaperdania: 'Bank Pesona Perdania',
      stalkabnamro: 'Bank ABN Amro',
      stalkkeppeltatlee: 'Bank Keppel Tatlee Buana',
      stalkbnpparibas: 'Bank BNP Paribas Indonesia',
      stalkwooriindonesia: 'Bank Woori Indonesia',
      stalkbumiarta: 'Bank Bumi Arta',
      stalkeconomy: 'Bank Ekonomi',
      stalkhaga: 'Bank Haga',
      stalkifi: 'Bank IFI',
      stalkjtrust: 'Bank Century/Bank J Trust Indonesia',
      stalkmayapada: 'Bank Mayapada',
      stalknusantaraparahyangan: 'Bank Nusantara Parahyangan',
      stalkswadesi: 'Bank Swadesi',
      stalkmestika: 'Bank Mestika',
      stalkmetroexpress: 'Bank Metro Express',
      stalkmaspion: 'Bank Maspion',
      stalkhagakita: 'Bank Hagakita',
      stalkganesha: 'Bank Ganesha',
      stalkwindukentjana: 'Bank Windu Kentjana',
      stalkicbc: 'Bank ICBC Indonesia',
      stalkharmoniinternasional: 'Bank Harmoni Internasional',
      stalkqnb: 'Bank QNB',
      stalkswaguna: 'Bank Swaguna',
      stalkmega: 'Bank Mega',
      stalkbukopin: 'Bank Bukopin',
      stalkbisnisinternasional: 'Bank Bisnis Internasional',
      stalksripartha: 'Bank Sri Partha',
      stalkkebhana: 'Bank KEB Hana Indonesia',
      stalkmncinternasional: 'Bank MNC Internasional',
      stalkneo: 'Bank Neo',
      stalkbniagro: 'Bank BNI Agro',
      stalknobu: 'Bank Nobu',
      stalkinaperdana: 'Bank Ina Perdana',
      stalksahabatsampoerna: 'Bank Sahabat Sampoerna',
      stalkseabank: 'SeaBank',
      stalkjago: 'Bank Jago',
      stalkmayora: 'Bank Mayora',
      stalkindexselindo: 'Bank Index Selindo',
      stalkallobank: 'AlloBank',
      stalkamericanexpress: 'Bank American Express Bank LTD',
      stalkjpmorganchase: 'Bank JP. Morgan Chase Bank, N.A',
      stalkcitibank: 'Bank Citibank',
      stalkofamerica: 'Bank of America, N.A',
      stalking: 'Bank ING Indonesia Bank',
      stalkchinaconstruction: 'Bank China Construction Bank Indonesia',
      stalkcreditagricole: 'Bank Credit Agricole Indosuez',
      stalkbangkok: 'Bank Bangkok',
      stalktokyomitsubishi: 'Bank of Tokyo Mitsubishi',
      stalksumitomomitsui: 'Bank Sumitomo Mitsui Indonesia',
      stalkdbs: 'Bank DBS Indonesia',
      stalkmihuzo: 'Bank Mihuzo Indonesia',
      stalkstandardchartered: 'Bank Standard Chartered',
      stalkcapital: 'Bank Capital Indonesia',
      stalkanz: 'Bank ANZ Indonesia',
      stalkchina: 'Bank of China Indonesia',
      stalkdeutsche: 'Bank Deutsche',
      stalkshinhan: 'Bank Shinhan Indonesia',
      stalkwoorisaudara: 'Bank Woori Saudara Indonesia',
      stalkcommonwealth: 'Bank Commonwealth',
      stalkcimbniagasyariah: 'Bank CIMB Niaga Syariah',
      stalkmuamalat: 'Bank Muamalat',
      stalkbjbsyariah: 'Bank BJB Syariah',
      stalkbsi: 'Bank Syariah Indonesia (BSI)',
      stalkmegasyariah: 'Bank Mega Syariah',
      stalkpanindubaisyariah: 'Bank Panin Dubai Syariah',
      stalkbukopinsyariah: 'Bank Bukopin Syariah',
      stalkbcasyariah: 'Bank BCA Syariah',
      stalkbtpnsyariah: 'Bank BTPN Syariah',
      stalkaladinsyariah: 'Bank Aladin Syariah'
    };
  
   // Jika filter disediakan, kembalikan nilai bank yang sesuai dengan filter
   if (filter) {
    const lowerCaseFilter = filter.toLowerCase();
    const filteredEntries = Object.entries(bankList).filter(([key, value]) =>
        key.toLowerCase().startsWith(lowerCaseFilter)
    );

    // Jika ada hasil yang sesuai, kembalikan hasil pertama
    if (filteredEntries.length > 0) {
        return filteredEntries[0][1]; // Mengembalikan nilai dari hasil pertama
    } else {
        return 'Bank tidak ditemukan'; // Pesan jika tidak ada hasil
    }
}
  
    // Jika tidak ada filter, kembalikan semua daftar bank
    return bankList;
  };

  module.exports = initializeBankList;
